config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:registrations, :passwords]
  resources :messages
  # resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: "messages#index"
end

app/models/message.rb
# TODO: Implement soft delete
class Message < ApplicationRecord
  has_many :accesses, dependent: :destroy
  has_many :users, through: :accesses

  validates :content, presence: true, length: {minimum: 1}

  scope :received, -> do
    includes(:accesses).where(accesses: {kind: :recipient})# `includes` (optimization only)
  end

  scope :sent, -> do
    includes(:accesses).where(accesses: {kind: :owner})
  end

  scope :im_sorted, -> {order created_at: :desc}

  # TODO: Error message passthrough
  def add_recipient *users
    is_committed = false

    Message.transaction do
      begin
        users.each do |user|
          Access.create!({message: self, kind: :recipient}.merge(
            user.instance_of?(User) ? {user: user} : {user_id: user}
          ))
        end
        is_committed = true
      rescue ActiveRecord::RecordInvalid
        raise ActiveRecord::Rollback
      end
    end

    is_committed
  end

  # TODO: Investigate optimization for `Access` rewrite
  def commit_with_recipient *users, attrib_updates
    is_committed = false

    Message.transaction do
      begin
        if self.new_record?
          self.save!
        else
          self.remove_recipients
          self.update_attributes! attrib_updates
        end

        users.each do |user|
          Access.create!({message: self, kind: :recipient}.merge(
            user.instance_of?(User) ? {user: user} : {user_id: user}
          ))
        end
        is_committed = true
      rescue ActiveRecord::RecordInvalid => e
        error = e.message.split(":")[-1].strip
          .match(/(?<name>\w*) (?<value>.*)/).named_captures
          .transform_values(&:downcase)
        self.errors.add *error.values

        raise ActiveRecord::Rollback
      end
    end

    is_committed
  end

  def sender
    accesses.find_by(kind: :owner).user
  end

  def recipients
    users.includes(:accesses).where accesses: {kind: :recipient}
  end

  # Returns the last recipient from recipient collection
  def recipient
    recipients.last
  end

  def remove_recipients
    self.accesses.where(accesses: {kind: :recipient}).destroy_all
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_message, only: [:show, :edit, :update, :destroy]
  before_action :load_recipients, only: [:new, :create, :edit]
  load_and_authorize_resource

  # GET /messages
  # GET /messages.json
  def index
    # @messages is automatically set to
    # Product.accessible_by(current_ability) by CanCanCan
    @messages = @messages.im_sorted
  end

  # GET /messages/1
  # GET /messages/1.json
  def show
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # GET /messages/1/edit
  def edit
  end

  # POST /messages
  # POST /messages.json
  def create
    @message = Message.new(message_params.merge users: [current_user])

    respond_to do |format|
      if @message.commit_with_recipient recipient_param, {}
        format.html { redirect_to @message, notice: 'Message was successfully created.' }
        format.json { render :show, status: :created, location: @message }
      else
        format.html { render :new }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /messages/1
  # PATCH/PUT /messages/1.json
  def update
    respond_to do |format|
      if @message.commit_with_recipient recipient_param, message_params
        format.html { redirect_to @message, notice: 'Message was successfully updated.' }
        format.json { render :show, status: :ok, location: @message }
      else
        format.html { render :edit }
        format.json { render json: @message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /messages/1
  # DELETE /messages/1.json
  def destroy
    @message.destroy
    respond_to do |format|
      format.html { redirect_to messages_url, notice: 'Message was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def message_params
      params.require(:message).permit(:content)
    end

    def recipient_param
      params[:recipient_id].to_i
    end

    def load_recipients
      @other_users = User.without current_user
    end
end

app/helpers/messages_helper.rb
# TODO: Move methods to decorator
module MessagesHelper
  def recipient_id message
    recipient = message.recipient
    recipient ? recipient.id : 0
  end

  def recipient_name message
    recipient = message.recipient
    recipient.full_name if recipient
  end

  def sender_name message
    sender = message.sender
    sender.full_name if sender
  end

  def authorized_edit_message_path message
    link_to("Edit", edit_message_path(@message)) if can? :update, message
  end
end

app/views/messages/_form.html.erb
<%= form_with(model: message, local: true) do |form| %>
  <% if message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

      <ul>
      <% message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_field :content, id: :message_content, required: true %>
    <%= form.label :recipient %>
    <%= select_tag :recipient_id,
      options_from_collection_for_select(@other_users, :id, :full_name,
      recipient_id(message)), prompt: "--- Select ---", required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<br>
<%= link_to 'New Message', new_message_path %>
<br><hr>

<h2>Received messages</h2>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>From</th>
      <th>Received at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.received.each do |message| %>
      <tr>
        <td><%= truncate message.content %></td>
        <td><%= sender_name message  %></td>
        <td class="local-time"><%= message.created_at.to_s %></td>
        <td><%= link_to 'Show', message %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br><hr>

<h2>Sent messages</h2>

<table>
  <thead>
  <tr>
    <th>Content</th>
    <th>Recipient</th>
    <th>Sent at</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @messages.sent.each do |message| %>
    <tr>
      <td><%= truncate message.content %></td>
      <td><%= recipient_name message  %></td>
      <td class="local-time"><%= message.created_at.to_s %></td>
      <td><%= link_to 'Show', message %></td>
      <td><%= link_to 'Edit', edit_message_path(message) %></td>
      <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br><hr>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>From:</strong>
  <%= @message.sender == current_user ? t("generic.me") : @message.sender.full_name %>
</p>

<p>
  <strong>To:</strong>
  <%= @message.recipient == current_user ? t("generic.me") : @message.recipient.full_name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @message.content %>
</p>

<%= authorized_edit_message_path @message %>&nbsp;
<%= link_to 'Back', messages_path %>